//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trinity.VSExtension {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrinityVSExtensionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrinityVSExtensionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Trinity.VSExtension.TrinityVSExtensionResources", typeof(TrinityVSExtensionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Icon.
        /// </summary>
        internal static string ApplicationIcon {
            get {
                return ResourceManager.GetString("ApplicationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets the .ico file to use as your application icon..
        /// </summary>
        internal static string ApplicationIconDescription {
            get {
                return ResourceManager.GetString("ApplicationIconDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly Name.
        /// </summary>
        internal static string AssemblyName {
            get {
                return ResourceManager.GetString("AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the output file that will hold assembly metadata..
        /// </summary>
        internal static string AssemblyNameDescription {
            get {
                return ResourceManager.GetString("AssemblyNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean source code after build.
        /// </summary>
        internal static string CleanSourceCodeAfterBuild {
            get {
                return ResourceManager.GetString("CleanSourceCodeAfterBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clean auto-generated source code files after a build. If disabled, you can find the generated source files in the bin\GeneratedCode folder..
        /// </summary>
        internal static string CleanSourceCodeAfterBuildDescription {
            get {
                return ResourceManager.GetString("CleanSourceCodeAfterBuildDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Namespace.
        /// </summary>
        internal static string DefaultNamespace {
            get {
                return ResourceManager.GetString("DefaultNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies the default namespace for added items, such as classes, that are added via the Add New Item Dialog Box..
        /// </summary>
        internal static string DefaultNamespaceDescription {
            get {
                return ResourceManager.GetString("DefaultNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralCaption {
            get {
                return ResourceManager.GetString("GeneralCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate debug symbols.
        /// </summary>
        internal static string GenerateDebugSymbols {
            get {
                return ResourceManager.GetString("GenerateDebugSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether to generate debug symbols(the .pdb file). The debug symbol file is necessary for debugging the generated code(e.g. stepping into the generated code, inspect the variables)..
        /// </summary>
        internal static string GenerateDebugSymbolsDescription {
            get {
                return ResourceManager.GetString("GenerateDebugSymbolsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        internal static string OutputFile {
            get {
                return ResourceManager.GetString("OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the project&apos;s primary output file..
        /// </summary>
        internal static string OutputFileDescription {
            get {
                return ResourceManager.GetString("OutputFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Type.
        /// </summary>
        internal static string OutputType {
            get {
                return ResourceManager.GetString("OutputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type of application to build..
        /// </summary>
        internal static string OutputTypeDescription {
            get {
                return ResourceManager.GetString("OutputTypeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File.
        /// </summary>
        internal static string ProjectFile {
            get {
                return ResourceManager.GetString("ProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the file containing build, configuration, and other information about the project..
        /// </summary>
        internal static string ProjectFileDescription {
            get {
                return ResourceManager.GetString("ProjectFileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Folder.
        /// </summary>
        internal static string ProjectFolder {
            get {
                return ResourceManager.GetString("ProjectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The absolute location of the project..
        /// </summary>
        internal static string ProjectFolderDescription {
            get {
                return ResourceManager.GetString("ProjectFolderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Root Namespace.
        /// </summary>
        internal static string RootNamespace {
            get {
                return ResourceManager.GetString("RootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The root namespace of the generated assembly.
        /// </summary>
        internal static string RootNamespaceDescription {
            get {
                return ResourceManager.GetString("RootNamespaceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Object.
        /// </summary>
        internal static string StartupObject {
            get {
                return ResourceManager.GetString("StartupObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the class that contains the static Main method that you want called when you launch your application..
        /// </summary>
        internal static string StartupObjectDescription {
            get {
                return ResourceManager.GetString("StartupObjectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Framework Moniker.
        /// </summary>
        internal static string TargetFrameworkMoniker {
            get {
                return ResourceManager.GetString("TargetFrameworkMoniker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version of the Common Language Runtime to use for output assembly..
        /// </summary>
        internal static string TargetFrameworkMonikerDescription {
            get {
                return ResourceManager.GetString("TargetFrameworkMonikerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TrinityProjectNodeIcon {
            get {
                object obj = ResourceManager.GetObject("TrinityProjectNodeIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon TSLFileNodeIcon {
            get {
                object obj = ResourceManager.GetObject("TSLFileNodeIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
