// ----------------------------------------------------------------------------
// <auto-generated>
// This is autogenerated code by CppSharp.
// Do not edit this file or all your changes will be lost after re-generation.
// </auto-generated>
// ----------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;
using System.Security;
using System.Runtime.CompilerServices;

[assembly:InternalsVisibleTo("asmjit")]

public unsafe partial class RTL_CRITICAL_SECTION
{
    [StructLayout(LayoutKind.Explicit, Size = 40)]
    public partial struct __Internal
    {
        [FieldOffset(0)]
        internal global::System.IntPtr DebugInfo;

        [FieldOffset(8)]
        internal int LockCount;

        [FieldOffset(12)]
        internal int RecursionCount;

        [FieldOffset(16)]
        internal global::System.IntPtr OwningThread;

        [FieldOffset(24)]
        internal global::System.IntPtr LockSemaphore;

        [FieldOffset(32)]
        internal ulong SpinCount;
    }
}
