# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_GraphEngine')).lstrip('.')
        return importlib.import_module(mname)
    _GraphEngine = swig_import_helper()
    del swig_import_helper
elif version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GraphEngine', [dirname(__file__)])
        except ImportError:
            import _GraphEngine
            return _GraphEngine
        if fp is not None:
            try:
                _mod = imp.load_module('_GraphEngine', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _GraphEngine = swig_import_helper()
    del swig_import_helper
else:
    import _GraphEngine
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def Init():
    return _GraphEngine.Init()
Init = _GraphEngine.Init

def LoadCell(cellId):
    return _GraphEngine.LoadCell(cellId)
LoadCell = _GraphEngine.LoadCell

def SaveCell(cellId, cell):
    return _GraphEngine.SaveCell(cellId, cell)
SaveCell = _GraphEngine.SaveCell

def SaveCell2(cellId, cell, options):
    return _GraphEngine.SaveCell2(cellId, cell, options)
SaveCell2 = _GraphEngine.SaveCell2

def NewCell(cellType):
    return _GraphEngine.NewCell(cellType)
NewCell = _GraphEngine.NewCell

def CellGetField(cell, field):
    return _GraphEngine.CellGetField(cell, field)
CellGetField = _GraphEngine.CellGetField

def CellSetField(cell, field, content):
    return _GraphEngine.CellSetField(cell, field, content)
CellSetField = _GraphEngine.CellSetField

def CellAppendField(cell, field, content):
    return _GraphEngine.CellAppendField(cell, field, content)
CellAppendField = _GraphEngine.CellAppendField

def CellRemoveField(cell, field):
    return _GraphEngine.CellRemoveField(cell, field)
CellRemoveField = _GraphEngine.CellRemoveField

def CellHasField(cell, field):
    return _GraphEngine.CellHasField(cell, field)
CellHasField = _GraphEngine.CellHasField

def CellDispose(cell):
    return _GraphEngine.CellDispose(cell)
CellDispose = _GraphEngine.CellDispose

def CellGetFieldNames(cell):
    return _GraphEngine.CellGetFieldNames(cell)
CellGetFieldNames = _GraphEngine.CellGetFieldNames
# This file is compatible with both classic and new-style classes.

cvar = _GraphEngine.cvar

