# For building Trinity only.

SET(RXCPP_DIR           ${TRINITY_SRC_DIR}/RxCpp)
SET(RX_INCLUDE_DIR      ${RXCPP_DIR}/Rx/v2/src/rxcpp)
SET(IX_INCLUDE_DIR      ${RXCPP_DIR}/Ix/CPP/src/cpplinq)

ADD_LIBRARY(Rx INTERFACE)
TARGET_INCLUDE_DIRECTORIES(Rx INTERFACE ${RX_INCLUDE_DIR})

ADD_LIBRARY(Ix INTERFACE)
TARGET_INCLUDE_DIRECTORIES(Ix INTERFACE ${IX_INCLUDE_DIR})
