# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.9
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_GraphEngine')).lstrip('.')
        return importlib.import_module(mname)
    _GraphEngine = swig_import_helper()
    del swig_import_helper
elif version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_GraphEngine', [dirname(__file__)])
        except ImportError:
            import _GraphEngine
            return _GraphEngine
        if fp is not None:
            try:
                _mod = imp.load_module('_GraphEngine', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _GraphEngine = swig_import_helper()
    del swig_import_helper
else:
    import _GraphEngine
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def Init():
    return _GraphEngine.Init()
Init = _GraphEngine.Init
class Cell(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Cell, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Cell, name)
    __repr__ = _swig_repr

    def __init__(self, cell):
        this = _GraphEngine.new_Cell(cell)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_setmethods__["m_cell"] = _GraphEngine.Cell_m_cell_set
    __swig_getmethods__["m_cell"] = _GraphEngine.Cell_m_cell_get
    if _newclass:
        m_cell = _swig_property(_GraphEngine.Cell_m_cell_get, _GraphEngine.Cell_m_cell_set)

    def GetField(self, field):
        return _GraphEngine.Cell_GetField(self, field)

    def SetField(self, field, content):
        return _GraphEngine.Cell_SetField(self, field, content)

    def AppendField(self, field, content):
        return _GraphEngine.Cell_AppendField(self, field, content)

    def RemoveField(self, field):
        return _GraphEngine.Cell_RemoveField(self, field)

    def HasField(self, field):
        return _GraphEngine.Cell_HasField(self, field)
    __swig_destroy__ = _GraphEngine.delete_Cell
    __del__ = lambda self: None

    def GetFieldNames(self):
        return _GraphEngine.Cell_GetFieldNames(self)
Cell_swigregister = _GraphEngine.Cell_swigregister
Cell_swigregister(Cell)
cvar = _GraphEngine.cvar


def LoadCell(cellId):
    return _GraphEngine.LoadCell(cellId)
LoadCell = _GraphEngine.LoadCell

def SaveCell_1(cellId, pcell):
    return _GraphEngine.SaveCell_1(cellId, pcell)
SaveCell_1 = _GraphEngine.SaveCell_1

def SaveCell_2(cellId, pcell, options):
    return _GraphEngine.SaveCell_2(cellId, pcell, options)
SaveCell_2 = _GraphEngine.SaveCell_2

def NewCell_1(cellType):
    return _GraphEngine.NewCell_1(cellType)
NewCell_1 = _GraphEngine.NewCell_1

def NewCell_2(cellId, cellType):
    return _GraphEngine.NewCell_2(cellId, cellType)
NewCell_2 = _GraphEngine.NewCell_2

def NewCell_3(cellType, cellContent):
    return _GraphEngine.NewCell_3(cellType, cellContent)
NewCell_3 = _GraphEngine.NewCell_3
# This file is compatible with both classic and new-style classes.


